#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-travis
Version  : 1.2
Release  : 8
URL      : https://rubygems.org/downloads/hoe-travis-1.2.gem
Source0  : https://rubygems.org/downloads/hoe-travis-1.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-travis-lint

%description
= hoe-travis
home :: https://github.com/drbrain/hoe-travis
rdoc :: http://docs.seattlerb.org/hoe-travis
bugs :: https://github.com/drbrain/hoe-travis/issues

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-travis-1.2
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-travis.gemspec

%build
gem build rubygem-hoe-travis.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-travis-1.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-travis-1.2
ruby -v -I.:lib:test test*/test_*.rb || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-travis-1.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/lib/hoe/travis.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-travis-1.2/test/test_hoe_travis.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-travis-1.2.gemspec
